#
# Module manifest for module 'PSMacToolkit'
#
# Generated by: Vincent Anso
#
# Generated on: 09/10/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PSMacToolkit.psm1'

# Version number of this module.
ModuleVersion = '2.0.0.0'

# Supported PSEditions
CompatiblePSEditions = @('Core')

# ID used to uniquely identify this module
GUID = '3b7b13a6-2d0e-47f8-ba5d-98b4cfc05803'

# Author of this module
Author = 'Vincent Anso'

# Company or vendor of this module
CompanyName = 'Vincent Anso'

# Copyright statement for this module
Copyright = '(c) Vincent Anso. All rights reserved.'

# Description of the functionality provided by this module
Description = 'This PowerShell module, ideal for macOS administrators and users, enhances user interactions and system management with a broad set of functions. These capabilities include common tasks, among others, such as file and folder selection, system information retrieval, clipboard operations, and user notifications. It also provides practical tools for managing Wi-Fi connections, 802.1X network profiles, and basic system actions like volume control, screen locking, and power management.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.2'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @( @{ ModuleName = 'PowerShellOSA' ; RequiredVersion = '1.0.0.0' } )
    
# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @(
    'PSMacToolkitLib.psm1',
    'StandardAdditions.psm1',
    'SystemInformation.psm1',
    'LoginWindow.psm1',
    'Network.psm1'
)


# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Select-Application',
    'Select-Color',
    'Select-File',
    'Select-FileName',
    'Select-Folder',
    'Select-FromList',
    'Select-RemoteApplication',
    'Select-URL',
    'Get-ClipboardInfo',
    'Get-InfoFor',
    'Get-ListDisks',
    'Get-ListFolder',
    'Get-LocalizedString',
    'Get-LocalizedStrings',
    'Get-MacClipboard',
    'Get-PathTo',
    'Get-PathToResource',
    'Get-ScriptingComponents',
    'Get-SPAvailableDataTypes',
    'Get-SPAvailableLocalizations',
    'Get-SPLocalizedString'
    'Get-SystemAttribute',
    'Get-SystemInfo',
    'Get-SystemInformation',
    'Get-UserCredential',
    'Get-VolumeSettings',
    'Invoke-Beep',
    'Invoke-DataDetection',
    'Invoke-Delay',
    'Invoke-Say',
    'Lock-Screen',
    'Disconnect-UserSession',
    'Mount-Volume',
    'Restart-MacComputer',
    'Set-MacClipboard',
    'Set-Volume',
    'Show-Alert',
    'Show-Dialog',
    'Show-Notification',
    'Stop-MacComputer',
    'Suspend-MacComputer',
    'Get-HardwareInfo',
    'Connect-WiFiNetwork',
    'Disconnect-WiFiNetwork',
    'Find-WiFiNetwork',
    'Get-WiFiNetworkInfo',
    'Get-WiFiPreferences',
    'Get-WiFiPreferredNetwork',
    'Get-WiFiState',
    'Set-WiFiState',
    'Connect-8021XWiFiNetwork',
    'Get-8021XConfigurationProfile',
    'Get-8021XNetworkInfo',
    'Get-8021XPreferences',
    'Start-8021XClient',
    'Stop-8021XClient',
    'Get-CurrentNetworkLocation',
    'Get-NetworkEthernetInterface',
    'Get-NetworkInfo',
    'Get-NetworkInterface',
    'Get-NetworkLocation',
    'Get-NetworkService',
    'Get-PrimaryNetworkInterface'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @(
    'Choose-Application',
    'Choose-Color',
    'Choose-File',
    'Choose-FileName',
    'Choose-Folder',
    'Choose-FromList',
    'Choose-RemoteApplication',
    'Choose-URL',
    'Display-Alert',
    'Display-Dialog',
    'Display-Notification',
    'Log-Out',
    'Sleep-MacComputer',
    'Connect-EnterpriseWiFiNetwork',
    'Get-EnterpriseConfigurationProfile',
    'Get-EnterpriseNetworkInfo',
    'Get-EnterprisePreferences',
    'Start-EnterpriseClient',
    'Stop-EnterpriseClient'
)

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('AppleScript','JavaScript','OSA','macOS','Mac','AppleEvents','Automation')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/vanso/PSMacToolkit/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/vanso/PSMacToolkit'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

